"""
Notification and Notification Channel Configuration Database Models
Stores security intelligence alerts, channel configurations, and read/delivery telemetry.
Conforms strictly to IMPLEMENT.md Section 33 (Step 32: Build Notifications).
"""

from datetime import datetime, timezone
import json
from typing import Any, Dict, Optional
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship
from app.models.base import BaseModel


class Notification(BaseModel):
    """
    Security intelligence notification generated by matching newly ingested content
    against active watchlists and computing composite importance.
    """

    __tablename__ = "notifications"

    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    session_id = Column(String(64), nullable=False, index=True)
    watchlist_id = Column(
        Integer,
        ForeignKey("watchlists.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    content_id = Column(
        Integer,
        ForeignKey("content.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    title = Column(String(255), nullable=False)
    body = Column(Text, nullable=False)
    summary = Column(Text, nullable=True)

    importance_score = Column(Float, nullable=False, default=0.5)
    importance_level = Column(String(20), nullable=False, default="MEDIUM", index=True)
    channel = Column(String(30), nullable=False, default="web", index=True)
    status = Column(String(30), nullable=False, default="delivered", index=True)

    is_read = Column(Boolean, default=False, nullable=False, index=True)
    read_at = Column(DateTime(timezone=True), nullable=True)

    # JSON metadata storing matched watchlist items, dispatch logs, headers, etc.
    metadata_json = Column(Text, nullable=True)

    # Relationships
    user = relationship("User", foreign_keys=[user_id])
    watchlist = relationship("Watchlist", foreign_keys=[watchlist_id])
    content = relationship("Content", foreign_keys=[content_id])

    __table_args__ = (
        Index("ix_notifications_session_read", session_id, is_read),
        Index("ix_notifications_session_importance", session_id, importance_level),
    )

    def to_dict(self) -> Dict[str, Any]:
        meta: Dict[str, Any] = {}
        if self.metadata_json:
            try:
                meta = json.loads(self.metadata_json)
            except Exception:
                meta = {"raw": self.metadata_json}

        # Resolve content title and canonical url if available
        c_title = None
        c_url = None
        if self.content:
            c_title = self.content.title
            c_url = self.content.canonical_url
        elif "content_title" in meta:
            c_title = meta.get("content_title")
            c_url = meta.get("content_url")

        w_name = None
        if self.watchlist:
            w_name = self.watchlist.name
        elif "watchlist_name" in meta:
            w_name = meta.get("watchlist_name")

        return {
            "id": self.id,
            "user_id": self.user_id,
            "session_id": self.session_id,
            "watchlist_id": self.watchlist_id,
            "watchlist_name": w_name,
            "content_id": self.content_id,
            "content_title": c_title,
            "content_url": c_url,
            "title": self.title,
            "body": self.body,
            "summary": self.summary,
            "importance_score": self.importance_score,
            "importance_level": self.importance_level,
            "channel": self.channel,
            "status": self.status,
            "is_read": self.is_read,
            "read_at": self.read_at.isoformat() if self.read_at else None,
            "metadata": meta,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self) -> str:
        return f"<Notification(id={self.id}, title='{self.title[:30]}', level='{self.importance_level}', channel='{self.channel}')>"


class NotificationChannelConfig(BaseModel):
    """
    User/Session configuration for notification delivery channels (Web, Email, Push, Webhook).
    Enforces minimum importance thresholds to avoid alert fatigue.
    """

    __tablename__ = "notification_channel_configs"

    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    session_id = Column(String(64), nullable=False, index=True)
    channel_type = Column(String(30), nullable=False, index=True)  # web, email, push, webhook
    destination = Column(String(255), nullable=True)  # email address, push endpoint, or webhook URL
    is_enabled = Column(Boolean, default=True, nullable=False)
    min_importance_threshold = Column(Float, default=0.50, nullable=False)
    secret_token = Column(String(128), nullable=True)  # HMAC signature key for webhooks
    description = Column(String(255), nullable=True)

    user = relationship("User", foreign_keys=[user_id])

    __table_args__ = (
        Index("ix_channel_configs_session_type", session_id, channel_type),
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "session_id": self.session_id,
            "channel_type": self.channel_type,
            "destination": self.destination,
            "is_enabled": self.is_enabled,
            "min_importance_threshold": self.min_importance_threshold,
            "secret_token": f"{self.secret_token[:4]}****" if self.secret_token else None,
            "description": self.description,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self) -> str:
        return f"<NotificationChannelConfig(id={self.id}, channel='{self.channel_type}', threshold={self.min_importance_threshold})>"
