"""add_remaining_production_models

Revision ID: c9a7ce69ab8e
Revises: 001_initial_schema
Create Date: 2026-09-18 22:41:25.463141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a7ce69ab8e'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_audits',
    sa.Column('audit_id', sa.String(length=100), nullable=False),
    sa.Column('architecture_status', sa.String(length=50), nullable=False),
    sa.Column('stages_count', sa.Integer(), nullable=False),
    sa.Column('stages_passed', sa.Integer(), nullable=False),
    sa.Column('triad_processing_passed', sa.Boolean(), nullable=False),
    sa.Column('triad_delivery_passed', sa.Boolean(), nullable=False),
    sa.Column('provenance_intact', sa.Boolean(), nullable=False),
    sa.Column('anti_patterns_checked', sa.Integer(), nullable=False),
    sa.Column('anti_patterns_prevented', sa.Integer(), nullable=False),
    sa.Column('prohibited_architecture', sa.String(length=100), nullable=False),
    sa.Column('target_cve', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('dag_traces_json', sa.JSON(), nullable=False),
    sa.Column('anti_patterns_json', sa.JSON(), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_audits_architecture_status'), 'architecture_audits', ['architecture_status'], unique=False)
    op.create_index(op.f('ix_architecture_audits_audit_id'), 'architecture_audits', ['audit_id'], unique=True)
    op.create_index(op.f('ix_architecture_audits_id'), 'architecture_audits', ['id'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('suite_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=False),
    sa.Column('recall_score', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('p95_latency_ms', sa.Float(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_runs_id'), 'benchmark_runs', ['id'], unique=False)
    op.create_index(op.f('ix_benchmark_runs_suite_name'), 'benchmark_runs', ['suite_name'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_sectors', sa.JSON(), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=False),
    sa.Column('malware_used', sa.JSON(), nullable=False),
    sa.Column('cves_exploited', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_actor_name'), 'campaigns', ['actor_name'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=True)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('compliance_audit_reports',
    sa.Column('audit_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dod_total_criteria', sa.Integer(), nullable=False),
    sa.Column('dod_passed_criteria', sa.Integer(), nullable=False),
    sa.Column('dod_score_pct', sa.Float(), nullable=False),
    sa.Column('milestones_total', sa.Integer(), nullable=False),
    sa.Column('milestones_passed', sa.Integer(), nullable=False),
    sa.Column('pipeline_integrity', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('pipeline_trace_json', sa.JSON(), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audit_reports_audit_id'), 'compliance_audit_reports', ['audit_id'], unique=True)
    op.create_index(op.f('ix_compliance_audit_reports_id'), 'compliance_audit_reports', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_reports_status'), 'compliance_audit_reports', ['status'], unique=False)
    op.create_table('connector_sync_states',
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('last_successful_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_sync_states_connector_id'), 'connector_sync_states', ['connector_id'], unique=True)
    op.create_index(op.f('ix_connector_sync_states_id'), 'connector_sync_states', ['id'], unique=False)
    op.create_table('correlation_clusters',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('matched_entities', sa.JSON(), nullable=False),
    sa.Column('source_items', sa.JSON(), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=False),
    sa.Column('first_observed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_clusters_id'), 'correlation_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_correlation_clusters_title'), 'correlation_clusters', ['title'], unique=False)
    op.create_table('dod_certificates',
    sa.Column('certificate_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('certified_by', sa.String(length=150), nullable=False),
    sa.Column('system_version', sa.String(length=50), nullable=False),
    sa.Column('compliance_score_pct', sa.Float(), nullable=False),
    sa.Column('total_criteria', sa.Integer(), nullable=False),
    sa.Column('passed_criteria', sa.Integer(), nullable=False),
    sa.Column('failed_criteria', sa.Integer(), nullable=False),
    sa.Column('pipeline_integrity', sa.String(length=50), nullable=False),
    sa.Column('sha256_signature', sa.String(length=128), nullable=False),
    sa.Column('checklist_proofs_json', sa.JSON(), nullable=False),
    sa.Column('markdown_certificate', sa.Text(), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dod_certificates_certificate_id'), 'dod_certificates', ['certificate_id'], unique=True)
    op.create_index(op.f('ix_dod_certificates_id'), 'dod_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_dod_certificates_status'), 'dod_certificates', ['status'], unique=False)
    op.create_table('golden_pipeline_runs',
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('feed_source', sa.String(length=255), nullable=False),
    sa.Column('article_title', sa.String(length=500), nullable=False),
    sa.Column('target_cve', sa.String(length=100), nullable=False),
    sa.Column('extracted_cves_json', sa.JSON(), nullable=False),
    sa.Column('classification_category', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('steps_passed', sa.Integer(), nullable=False),
    sa.Column('search_indexed', sa.Boolean(), nullable=False),
    sa.Column('query_latency_ms', sa.Float(), nullable=False),
    sa.Column('total_duration_ms', sa.Float(), nullable=False),
    sa.Column('step_traces_json', sa.JSON(), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_pipeline_runs_id'), 'golden_pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_golden_pipeline_runs_run_id'), 'golden_pipeline_runs', ['run_id'], unique=True)
    op.create_table('incident_timelines',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('incident_name', sa.String(length=255), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timelines_id'), 'incident_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_incident_timelines_incident_name'), 'incident_timelines', ['incident_name'], unique=False)
    op.create_index(op.f('ix_incident_timelines_title'), 'incident_timelines', ['title'], unique=False)
    op.create_table('learning_paths',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_learning_paths_role'), 'learning_paths', ['role'], unique=False)
    op.create_index(op.f('ix_learning_paths_slug'), 'learning_paths', ['slug'], unique=True)
    op.create_table('malware_families',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('malware_type', sa.String(length=100), nullable=False),
    sa.Column('target_platforms', sa.JSON(), nullable=False),
    sa.Column('mitre_software_id', sa.String(length=50), nullable=True),
    sa.Column('yara_rules', sa.JSON(), nullable=False),
    sa.Column('sample_hashes', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_actors', sa.JSON(), nullable=False),
    sa.Column('associated_cves', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malware_families_id'), 'malware_families', ['id'], unique=False)
    op.create_index(op.f('ix_malware_families_malware_type'), 'malware_families', ['malware_type'], unique=False)
    op.create_index(op.f('ix_malware_families_mitre_software_id'), 'malware_families', ['mitre_software_id'], unique=False)
    op.create_index(op.f('ix_malware_families_name'), 'malware_families', ['name'], unique=True)
    op.create_index(op.f('ix_malware_families_severity'), 'malware_families', ['severity'], unique=False)
    op.create_table('marketplace_connectors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_connectors_category'), 'marketplace_connectors', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_connectors_id'), 'marketplace_connectors', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_connectors_is_installed'), 'marketplace_connectors', ['is_installed'], unique=False)
    op.create_index(op.f('ix_marketplace_connectors_is_verified'), 'marketplace_connectors', ['is_verified'], unique=False)
    op.create_index(op.f('ix_marketplace_connectors_name'), 'marketplace_connectors', ['name'], unique=True)
    op.create_index(op.f('ix_marketplace_connectors_slug'), 'marketplace_connectors', ['slug'], unique=True)
    op.create_table('mitre_data_sources',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_data_sources_external_id'), 'mitre_data_sources', ['external_id'], unique=True)
    op.create_index(op.f('ix_mitre_data_sources_id'), 'mitre_data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_data_sources_name'), 'mitre_data_sources', ['name'], unique=False)
    op.create_table('mitre_groups',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_groups_external_id'), 'mitre_groups', ['external_id'], unique=True)
    op.create_index(op.f('ix_mitre_groups_id'), 'mitre_groups', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_groups_name'), 'mitre_groups', ['name'], unique=False)
    op.create_table('mitre_mitigations',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_mitigations_external_id'), 'mitre_mitigations', ['external_id'], unique=True)
    op.create_index(op.f('ix_mitre_mitigations_id'), 'mitre_mitigations', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_mitigations_name'), 'mitre_mitigations', ['name'], unique=False)
    op.create_table('mitre_relationships',
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'relationship', 'target_id', name='uq_mitre_source_rel_target')
    )
    op.create_index(op.f('ix_mitre_relationships_id'), 'mitre_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_relationships_relationship'), 'mitre_relationships', ['relationship'], unique=False)
    op.create_index(op.f('ix_mitre_relationships_source_id'), 'mitre_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_mitre_relationships_source_type'), 'mitre_relationships', ['source_type'], unique=False)
    op.create_index(op.f('ix_mitre_relationships_target_id'), 'mitre_relationships', ['target_id'], unique=False)
    op.create_index(op.f('ix_mitre_relationships_target_type'), 'mitre_relationships', ['target_type'], unique=False)
    op.create_table('mitre_software',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('software_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_software_external_id'), 'mitre_software', ['external_id'], unique=True)
    op.create_index(op.f('ix_mitre_software_id'), 'mitre_software', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_software_name'), 'mitre_software', ['name'], unique=False)
    op.create_table('mitre_tactics',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_tactics_external_id'), 'mitre_tactics', ['external_id'], unique=True)
    op.create_index(op.f('ix_mitre_tactics_id'), 'mitre_tactics', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_tactics_name'), 'mitre_tactics', ['name'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tactic_id', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('platforms', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_external_id'), 'mitre_techniques', ['external_id'], unique=True)
    op.create_index(op.f('ix_mitre_techniques_id'), 'mitre_techniques', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_name'), 'mitre_techniques', ['name'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_parent_id'), 'mitre_techniques', ['parent_id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_tactic_id'), 'mitre_techniques', ['tactic_id'], unique=False)
    op.create_table('region_nodes',
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('replication_lag_ms', sa.Float(), nullable=False),
    sa.Column('active_connections', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_nodes_id'), 'region_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_region_nodes_region_code'), 'region_nodes', ['region_code'], unique=True)
    op.create_index(op.f('ix_region_nodes_role'), 'region_nodes', ['role'], unique=False)
    op.create_index(op.f('ix_region_nodes_status'), 'region_nodes', ['status'], unique=False)
    op.create_table('source_reputations',
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('corroboration_rate', sa.Float(), nullable=False),
    sa.Column('false_positive_rate', sa.Float(), nullable=False),
    sa.Column('latency_rating_ms', sa.Float(), nullable=False),
    sa.Column('total_items_evaluated', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_reputations_id'), 'source_reputations', ['id'], unique=False)
    op.create_index(op.f('ix_source_reputations_reputation_score'), 'source_reputations', ['reputation_score'], unique=False)
    op.create_index(op.f('ix_source_reputations_source_name'), 'source_reputations', ['source_name'], unique=True)
    op.create_index(op.f('ix_source_reputations_tier'), 'source_reputations', ['tier'], unique=False)
    op.create_table('threat_actors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('motivation', sa.String(length=100), nullable=True),
    sa.Column('target_sectors', sa.JSON(), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mitre_group_id', sa.String(length=50), nullable=True),
    sa.Column('threat_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('associated_malware', sa.JSON(), nullable=False),
    sa.Column('associated_cves', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_actors_country'), 'threat_actors', ['country'], unique=False)
    op.create_index(op.f('ix_threat_actors_id'), 'threat_actors', ['id'], unique=False)
    op.create_index(op.f('ix_threat_actors_mitre_group_id'), 'threat_actors', ['mitre_group_id'], unique=False)
    op.create_index(op.f('ix_threat_actors_motivation'), 'threat_actors', ['motivation'], unique=False)
    op.create_index(op.f('ix_threat_actors_name'), 'threat_actors', ['name'], unique=True)
    op.create_index(op.f('ix_threat_actors_status'), 'threat_actors', ['status'], unique=False)
    op.create_index(op.f('ix_threat_actors_threat_level'), 'threat_actors', ['threat_level'], unique=False)
    op.create_table('notification_channel_configs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_importance_threshold', sa.Float(), nullable=False),
    sa.Column('secret_token', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_configs_session_type', 'notification_channel_configs', ['session_id', 'channel_type'], unique=False)
    op.create_index(op.f('ix_notification_channel_configs_channel_type'), 'notification_channel_configs', ['channel_type'], unique=False)
    op.create_index(op.f('ix_notification_channel_configs_id'), 'notification_channel_configs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_channel_configs_session_id'), 'notification_channel_configs', ['session_id'], unique=False)
    op.create_index(op.f('ix_notification_channel_configs_user_id'), 'notification_channel_configs', ['user_id'], unique=False)
    op.create_table('source_quality',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('authority', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('technical_depth', sa.Float(), nullable=False),
    sa.Column('originality', sa.Float(), nullable=False),
    sa.Column('historical_reliability', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('quality_tier', sa.String(length=64), nullable=False),
    sa.Column('indicator_symbol', sa.String(length=10), nullable=False),
    sa.Column('eval_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_quality_id'), 'source_quality', ['id'], unique=False)
    op.create_index(op.f('ix_source_quality_source_id'), 'source_quality', ['source_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('interests_json', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('preferred_types_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_session_id'), 'user_profiles', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_channel', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_watchlists_is_active'), 'watchlists', ['is_active'], unique=False)
    op.create_index('ix_watchlists_session_active', 'watchlists', ['session_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_watchlists_session_id'), 'watchlists', ['session_id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('content_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_tokens', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_chunks_content_id'), 'content_chunks', ['content_id'], unique=False)
    op.create_table('content_summaries',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('reported_facts', sa.Text(), nullable=True),
    sa.Column('inferences', sa.Text(), nullable=True),
    sa.Column('uncertainties', sa.Text(), nullable=True),
    sa.Column('key_takeaways', sa.Text(), nullable=True),
    sa.Column('source_attribution', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_summaries_content_id'), 'content_summaries', ['content_id'], unique=True)
    op.create_index(op.f('ix_content_summaries_id'), 'content_summaries', ['id'], unique=False)
    op.create_table('duplicate_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dup_cluster_canonical', 'duplicate_links', ['cluster_id', 'canonical_id'], unique=False)
    op.create_index(op.f('ix_duplicate_links_canonical_id'), 'duplicate_links', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_duplicate_links_cluster_id'), 'duplicate_links', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_duplicate_links_duplicate_id'), 'duplicate_links', ['duplicate_id'], unique=False)
    op.create_index(op.f('ix_duplicate_links_match_type'), 'duplicate_links', ['match_type'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_content_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_content_id'], ['content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'relationship', 'target_entity_id', 'source_content_id', name='uq_entity_rel_source_target_content')
    )
    op.create_index(op.f('ix_entity_relationships_id'), 'entity_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relationship'), 'entity_relationships', ['relationship'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_content_id'), 'entity_relationships', ['source_content_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('importance_level', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_content_id'), 'notifications', ['content_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_importance_level'), 'notifications', ['importance_level'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_session_id'), 'notifications', ['session_id'], unique=False)
    op.create_index('ix_notifications_session_importance', 'notifications', ['session_id', 'importance_level'], unique=False)
    op.create_index('ix_notifications_session_read', 'notifications', ['session_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_watchlist_id'), 'notifications', ['watchlist_id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(length=30), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_content_id'), 'user_interactions', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_created_at'), 'user_interactions', ['created_at'], unique=False)
    op.create_index('ix_user_interactions_created_at_desc', 'user_interactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_user_interactions_interaction_type'), 'user_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_user_interactions_search_query'), 'user_interactions', ['search_query'], unique=False)
    op.create_index('ix_user_interactions_session_content', 'user_interactions', ['session_id', 'content_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_session_id'), 'user_interactions', ['session_id'], unique=False)
    op.create_index('ix_user_interactions_session_type', 'user_interactions', ['session_id', 'interaction_type'], unique=False)
    op.create_index(op.f('ix_user_interactions_user_id'), 'user_interactions', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_value', sa.String(length=255), nullable=False),
    sa.Column('severity_threshold', sa.String(length=20), nullable=True),
    sa.Column('notify_on_match', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_item_type'), 'watchlist_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_watchlist_items_item_value'), 'watchlist_items', ['item_value'], unique=False)
    op.create_index('ix_watchlist_items_type_value', 'watchlist_items', ['item_type', 'item_value'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_index('ix_watchlist_items_watchlist_type', 'watchlist_items', ['watchlist_id', 'item_type'], unique=False)
    op.create_index('ix_content_published_at_desc', 'content', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('ix_content_source_published', 'content', ['source_id', sa.literal_column('published_at DESC')], unique=False)
    op.create_index('ix_content_type_published', 'content', ['content_type', sa.literal_column('published_at DESC')], unique=False)
    op.drop_index(op.f('ix_content_entities_id'), table_name='content_entities')
    op.drop_index(op.f('ix_content_tags_id'), table_name='content_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_tags_id'), 'content_tags', ['id'], unique=False)
    op.create_index(op.f('ix_content_entities_id'), 'content_entities', ['id'], unique=False)
    op.drop_index('ix_content_type_published', table_name='content')
    op.drop_index('ix_content_source_published', table_name='content')
    op.drop_index('ix_content_published_at_desc', table_name='content')
    op.drop_index('ix_watchlist_items_watchlist_type', table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index('ix_watchlist_items_type_value', table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_item_value'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_item_type'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_user_interactions_user_id'), table_name='user_interactions')
    op.drop_index('ix_user_interactions_session_type', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_session_id'), table_name='user_interactions')
    op.drop_index('ix_user_interactions_session_content', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_search_query'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_interaction_type'), table_name='user_interactions')
    op.drop_index('ix_user_interactions_created_at_desc', table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_created_at'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_content_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_notifications_watchlist_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index('ix_notifications_session_read', table_name='notifications')
    op.drop_index('ix_notifications_session_importance', table_name='notifications')
    op.drop_index(op.f('ix_notifications_session_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_importance_level'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_content_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_content_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_relationship'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_duplicate_links_match_type'), table_name='duplicate_links')
    op.drop_index(op.f('ix_duplicate_links_duplicate_id'), table_name='duplicate_links')
    op.drop_index(op.f('ix_duplicate_links_cluster_id'), table_name='duplicate_links')
    op.drop_index(op.f('ix_duplicate_links_canonical_id'), table_name='duplicate_links')
    op.drop_index('ix_dup_cluster_canonical', table_name='duplicate_links')
    op.drop_table('duplicate_links')
    op.drop_index(op.f('ix_content_summaries_id'), table_name='content_summaries')
    op.drop_index(op.f('ix_content_summaries_content_id'), table_name='content_summaries')
    op.drop_table('content_summaries')
    op.drop_index(op.f('ix_content_chunks_content_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_session_id'), table_name='watchlists')
    op.drop_index('ix_watchlists_session_active', table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_is_active'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_session_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_source_quality_source_id'), table_name='source_quality')
    op.drop_index(op.f('ix_source_quality_id'), table_name='source_quality')
    op.drop_table('source_quality')
    op.drop_index(op.f('ix_notification_channel_configs_user_id'), table_name='notification_channel_configs')
    op.drop_index(op.f('ix_notification_channel_configs_session_id'), table_name='notification_channel_configs')
    op.drop_index(op.f('ix_notification_channel_configs_id'), table_name='notification_channel_configs')
    op.drop_index(op.f('ix_notification_channel_configs_channel_type'), table_name='notification_channel_configs')
    op.drop_index('ix_channel_configs_session_type', table_name='notification_channel_configs')
    op.drop_table('notification_channel_configs')
    op.drop_index(op.f('ix_threat_actors_threat_level'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_status'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_name'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_motivation'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_mitre_group_id'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_id'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_country'), table_name='threat_actors')
    op.drop_table('threat_actors')
    op.drop_index(op.f('ix_source_reputations_tier'), table_name='source_reputations')
    op.drop_index(op.f('ix_source_reputations_source_name'), table_name='source_reputations')
    op.drop_index(op.f('ix_source_reputations_reputation_score'), table_name='source_reputations')
    op.drop_index(op.f('ix_source_reputations_id'), table_name='source_reputations')
    op.drop_table('source_reputations')
    op.drop_index(op.f('ix_region_nodes_status'), table_name='region_nodes')
    op.drop_index(op.f('ix_region_nodes_role'), table_name='region_nodes')
    op.drop_index(op.f('ix_region_nodes_region_code'), table_name='region_nodes')
    op.drop_index(op.f('ix_region_nodes_id'), table_name='region_nodes')
    op.drop_table('region_nodes')
    op.drop_index(op.f('ix_mitre_techniques_tactic_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_parent_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_name'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_external_id'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_mitre_tactics_name'), table_name='mitre_tactics')
    op.drop_index(op.f('ix_mitre_tactics_id'), table_name='mitre_tactics')
    op.drop_index(op.f('ix_mitre_tactics_external_id'), table_name='mitre_tactics')
    op.drop_table('mitre_tactics')
    op.drop_index(op.f('ix_mitre_software_name'), table_name='mitre_software')
    op.drop_index(op.f('ix_mitre_software_id'), table_name='mitre_software')
    op.drop_index(op.f('ix_mitre_software_external_id'), table_name='mitre_software')
    op.drop_table('mitre_software')
    op.drop_index(op.f('ix_mitre_relationships_target_type'), table_name='mitre_relationships')
    op.drop_index(op.f('ix_mitre_relationships_target_id'), table_name='mitre_relationships')
    op.drop_index(op.f('ix_mitre_relationships_source_type'), table_name='mitre_relationships')
    op.drop_index(op.f('ix_mitre_relationships_source_id'), table_name='mitre_relationships')
    op.drop_index(op.f('ix_mitre_relationships_relationship'), table_name='mitre_relationships')
    op.drop_index(op.f('ix_mitre_relationships_id'), table_name='mitre_relationships')
    op.drop_table('mitre_relationships')
    op.drop_index(op.f('ix_mitre_mitigations_name'), table_name='mitre_mitigations')
    op.drop_index(op.f('ix_mitre_mitigations_id'), table_name='mitre_mitigations')
    op.drop_index(op.f('ix_mitre_mitigations_external_id'), table_name='mitre_mitigations')
    op.drop_table('mitre_mitigations')
    op.drop_index(op.f('ix_mitre_groups_name'), table_name='mitre_groups')
    op.drop_index(op.f('ix_mitre_groups_id'), table_name='mitre_groups')
    op.drop_index(op.f('ix_mitre_groups_external_id'), table_name='mitre_groups')
    op.drop_table('mitre_groups')
    op.drop_index(op.f('ix_mitre_data_sources_name'), table_name='mitre_data_sources')
    op.drop_index(op.f('ix_mitre_data_sources_id'), table_name='mitre_data_sources')
    op.drop_index(op.f('ix_mitre_data_sources_external_id'), table_name='mitre_data_sources')
    op.drop_table('mitre_data_sources')
    op.drop_index(op.f('ix_marketplace_connectors_slug'), table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_name'), table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_is_verified'), table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_is_installed'), table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_id'), table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_category'), table_name='marketplace_connectors')
    op.drop_table('marketplace_connectors')
    op.drop_index(op.f('ix_malware_families_severity'), table_name='malware_families')
    op.drop_index(op.f('ix_malware_families_name'), table_name='malware_families')
    op.drop_index(op.f('ix_malware_families_mitre_software_id'), table_name='malware_families')
    op.drop_index(op.f('ix_malware_families_malware_type'), table_name='malware_families')
    op.drop_index(op.f('ix_malware_families_id'), table_name='malware_families')
    op.drop_table('malware_families')
    op.drop_index(op.f('ix_learning_paths_slug'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_role'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_incident_timelines_title'), table_name='incident_timelines')
    op.drop_index(op.f('ix_incident_timelines_incident_name'), table_name='incident_timelines')
    op.drop_index(op.f('ix_incident_timelines_id'), table_name='incident_timelines')
    op.drop_table('incident_timelines')
    op.drop_index(op.f('ix_golden_pipeline_runs_run_id'), table_name='golden_pipeline_runs')
    op.drop_index(op.f('ix_golden_pipeline_runs_id'), table_name='golden_pipeline_runs')
    op.drop_table('golden_pipeline_runs')
    op.drop_index(op.f('ix_dod_certificates_status'), table_name='dod_certificates')
    op.drop_index(op.f('ix_dod_certificates_id'), table_name='dod_certificates')
    op.drop_index(op.f('ix_dod_certificates_certificate_id'), table_name='dod_certificates')
    op.drop_table('dod_certificates')
    op.drop_index(op.f('ix_correlation_clusters_title'), table_name='correlation_clusters')
    op.drop_index(op.f('ix_correlation_clusters_id'), table_name='correlation_clusters')
    op.drop_table('correlation_clusters')
    op.drop_index(op.f('ix_connector_sync_states_id'), table_name='connector_sync_states')
    op.drop_index(op.f('ix_connector_sync_states_connector_id'), table_name='connector_sync_states')
    op.drop_table('connector_sync_states')
    op.drop_index(op.f('ix_compliance_audit_reports_status'), table_name='compliance_audit_reports')
    op.drop_index(op.f('ix_compliance_audit_reports_id'), table_name='compliance_audit_reports')
    op.drop_index(op.f('ix_compliance_audit_reports_audit_id'), table_name='compliance_audit_reports')
    op.drop_table('compliance_audit_reports')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_actor_name'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_benchmark_runs_suite_name'), table_name='benchmark_runs')
    op.drop_index(op.f('ix_benchmark_runs_id'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_architecture_audits_id'), table_name='architecture_audits')
    op.drop_index(op.f('ix_architecture_audits_audit_id'), table_name='architecture_audits')
    op.drop_index(op.f('ix_architecture_audits_architecture_status'), table_name='architecture_audits')
    op.drop_table('architecture_audits')
    # ### end Alembic commands ###
